import Head from "next/head";
import { Inter } from "@next/font/google";

import { Login } from "../components/Login";
import authProtectedLogin from "@/components/authProtectedLogin";

function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </>
  );
}

export default authProtectedLogin(Home);
